sudo: required
services:
  - docker

before_install:
  - docker build -t seneka810/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true seneka810/react-test npm test

after_success:
  - docker build -t seneka810/multi-client ./client
  - docker build -t seneka810/multi-nginx ./nginx
  - docker build -t seneka810/multi-server ./server
  - docker build -t seneka810/multi-worker ./worker
  
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push seneka810/multi-client
  - docker push seneka810/multi-nginx
  - docker push seneka810/multi-server
  - docker push seneka810/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'Multidocker-env-1'
  bucket_name: 'elasticbeanstalk-us-east-1-976116225930'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY